export const CREATE_NEW_CURRENT_TASK = 'CREATE_NEW_CURRENT_TASK';
export const SET_TASK_TITLE          = 'SET_TASK_TITLE';
export const START_TASK_PROGRESS     = 'START_TASK_PROGRESS';
export const STOP_TASK_PROGRESS      = 'STOP_TASK_PROGRESS';
export const DELETE_TASK             = 'DELETE_TASK';
export const DELETE_TIMELOGS         = 'DELETE_TIMELOGS';
export const ADD_TIME_LOG_TO_TASK    = 'ADD_TIME_LOG_TO_TASK';

export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SET_PROJECT_TITLE = 'SET_PROJECT_TITLE';
