export const CREATE_NEW_CURRENT_TASK = 'CREATE_NEW_CURRENT_TASK';
export const SET_TASK_TITLE = 'SET_TASK_TITLE';
export const START_TASK_PROGRESS = 'START_TASK_PROGRESS';
export const STOP_TASK_PROGRRESS = 'STOP_TASK_PROGRESS';
